version: "3.9"
services:
  nebual-db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "${PG_PORT-5432}:5432"
    environment:
      DATABASE_HOST: ${PG_HOST:-127.0.0.1}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWD:-docker}
      POSTGRES_PORT: 5432
      POSTGRES_DB: nebula
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
